# Generated by Django 2.2.1 on 2019-09-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_level_1', models.CharField(max_length=30, verbose_name='category_level_1')),
                ('category_level_2', models.CharField(max_length=30, verbose_name='category_level_2')),
                ('category_level_3', models.CharField(max_length=30, verbose_name='category_level_3')),
                ('category_level_4', models.CharField(max_length=30, verbose_name='category_level_4')),
                ('category_level_5', models.CharField(max_length=30, verbose_name='category_level_5')),
            ],
        ),
        migrations.CreateModel(
            name='Banners_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='banner_image/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category_level_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Category_level_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_L2_name', models.CharField(max_length=30, verbose_name='category_L2_name')),
                ('CL1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Category_level_1')),
            ],
        ),
        migrations.CreateModel(
            name='Category_level_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_L3_name', models.CharField(max_length=30, verbose_name='category_L3_name')),
                ('CL2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Category_level_2')),
            ],
        ),
        migrations.CreateModel(
            name='Category_level_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_L4_name', models.CharField(max_length=30, verbose_name='category_L4_name')),
                ('CL3_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Category_level_3')),
            ],
        ),
        migrations.CreateModel(
            name='Color_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10, verbose_name='Header')),
                ('sidebar', models.CharField(max_length=10, verbose_name='Sidebar')),
                ('background_color', models.CharField(max_length=10, verbose_name='Background_color')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.CharField(max_length=300, verbose_name='full_description')),
                ('main_description', models.CharField(max_length=100, verbose_name='main_description')),
            ],
        ),
        migrations.CreateModel(
            name='Main_Image_and_Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.FileField(upload_to='product_images/')),
                ('thumbnail', models.FileField(upload_to='product_thumbanails/')),
                ('url_of_videos', models.FileField(upload_to='product_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_qty_advanced_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_stock', models.BooleanField(default=False)),
                ('out_of_stock_threshold', models.CharField(max_length=10, verbose_name='out_of_stock_threshold')),
                ('min_qty_allowed_in_cart', models.CharField(max_length=10, verbose_name='min_qty_allowed_in_cart')),
                ('max_qty_allowed_in_cart', models.CharField(max_length=10, verbose_name='max_qty_allowed_in_cart')),
                ('qty_uses_decimal', models.BooleanField(default=False)),
                ('allow_multi_box_of_shipping', models.BooleanField(default=False)),
                ('back_orders', models.CharField(max_length=40, verbose_name='back_orders')),
                ('notify_for_qty_below', models.CharField(max_length=10, verbose_name='notify_for_qty_below')),
                ('enable_qty_increments', models.BooleanField(default=False)),
                ('stock_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_design_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_design_start', models.CharField(max_length=20, verbose_name='schedule_design_start')),
                ('schedule_design_end', models.CharField(max_length=20, verbose_name='schedule_design_end')),
                ('new_theme', models.CharField(max_length=20, verbose_name='new_theme')),
                ('new_layout', models.CharField(max_length=20, verbose_name='new_layout')),
            ],
        ),
        migrations.CreateModel(
            name='Search_Engine_Optimization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(max_length=40, verbose_name='URL_KEY')),
                ('meta_title', models.CharField(max_length=50, verbose_name='meta_title')),
                ('meta_keywords', models.CharField(max_length=50, verbose_name='meta_keywords')),
                ('meta_description', models.CharField(max_length=200, verbose_name='meta_description')),
            ],
        ),
        migrations.CreateModel(
            name='Special_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_price_from', models.CharField(max_length=20, verbose_name='special_price_from')),
                ('special_price_to', models.CharField(max_length=20, verbose_name='special_price_to')),
                ('special_price', models.CharField(max_length=10, verbose_name='special_price')),
                ('special_cost', models.CharField(max_length=10, verbose_name='special_cost')),
                ('mfr_suggested_retailer_price', models.CharField(max_length=10, verbose_name='mfr_suggested_retailer_price')),
                ('disp_actual_price', models.CharField(max_length=30, verbose_name='disp_actual_price')),
            ],
        ),
        migrations.CreateModel(
            name='Set_of_Images_and_Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_of_images', models.FileField(upload_to='set_of_product_images/')),
                ('main_img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Main_Image_and_Videos')),
            ],
        ),
        migrations.CreateModel(
            name='Category_level_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_L5_name', models.CharField(max_length=30, verbose_name='category_L5_name')),
                ('CL4_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Category_level_4')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_product_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_name')),
                ('product_price', models.CharField(max_length=10, verbose_name='product_price')),
                ('tax_class', models.CharField(max_length=20, verbose_name='tax_class')),
                ('product_quantity', models.CharField(max_length=10, verbose_name='product_quantity')),
                ('length', models.CharField(max_length=10, verbose_name='length')),
                ('width', models.CharField(max_length=10, verbose_name='width')),
                ('height', models.CharField(max_length=10, verbose_name='height')),
                ('weight', models.CharField(max_length=10, verbose_name='weight')),
                ('brand_name', models.CharField(max_length=30, verbose_name='brand_name')),
                ('visibility', models.CharField(max_length=30, verbose_name='visibility')),
                ('set_pro_new_from', models.CharField(max_length=20, verbose_name='set_pro_new_from')),
                ('set_pro_new_to', models.CharField(max_length=20, verbose_name='set_pro_new_to')),
                ('featured', models.BooleanField(default=False)),
                ('gift', models.BooleanField(default=False)),
                ('adv_inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Pro_qty_advanced_inventory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.All_categories')),
                ('contents_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Contents')),
                ('main_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Main_Image_and_Videos')),
                ('schedule_design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Schedule_design_update')),
                ('seo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Search_Engine_Optimization')),
                ('special_price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipmart.Special_price')),
            ],
        ),
    ]
