# Generated by Django 2.2.1 on 2019-07-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_name')),
                ('product_quantity', models.CharField(max_length=20, verbose_name='product_quantity')),
                ('product_price', models.CharField(max_length=20, verbose_name='product_price')),
                ('category', models.CharField(max_length=20, verbose_name='product_quantity')),
                ('product_details', models.CharField(max_length=100, verbose_name='product_details')),
            ],
        ),
    ]
