# Generated by Django 2.2.1 on 2019-07-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0002_category_level_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_level_1',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category_level_1',
            name='category_L1_name',
            field=models.CharField(default=1, max_length=30, verbose_name='category_L1_name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category_level_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_L2_name', models.CharField(max_length=30, verbose_name='category_L2_name')),
                ('CL1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Category_level_1')),
            ],
        ),
    ]
