# Generated by Django 2.2.1 on 2019-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0003_auto_20190707_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_level_1',
            name='category_L1_name',
        ),
        migrations.AddField(
            model_name='category_level_1',
            name='category_name',
            field=models.CharField(default=1, max_length=30, verbose_name='category_name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category_level_2',
        ),
    ]
