# Generated by Django 2.2.1 on 2019-07-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0006_category_level_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_level_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_L4_name', models.CharField(max_length=30, verbose_name='category_L4_name')),
                ('CL3_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Category_level_3')),
            ],
        ),
    ]
