# Generated by Django 2.2.1 on 2019-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0008_category_level_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_level_1', models.CharField(max_length=30, verbose_name='category_level_1')),
                ('category_level_2', models.CharField(max_length=30, verbose_name='category_level_2')),
                ('category_level_3', models.CharField(max_length=30, verbose_name='category_level_3')),
                ('category_level_4', models.CharField(max_length=30, verbose_name='category_level_4')),
                ('category_level_5', models.CharField(max_length=30, verbose_name='category_level_5')),
            ],
        ),
    ]
