# Generated by Django 2.2.1 on 2019-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0009_all_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
