# Generated by Django 2.2.1 on 2019-07-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0014_auto_20190713_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_image',
            name='image',
            field=models.FileField(upload_to='banner_image/'),
        ),
    ]
