# Generated by Django 2.2.1 on 2019-07-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0015_auto_20190713_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10, verbose_name='Header')),
                ('sidebar', models.CharField(max_length=10, verbose_name='Sidebar')),
                ('background_color', models.CharField(max_length=10, verbose_name='Background_color')),
            ],
        ),
    ]
