# Generated by Django 2.2.1 on 2019-07-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0016_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners_image',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
