# Generated by Django 2.2.1 on 2019-07-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0019_auto_20190716_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_image',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
