# Generated by Django 2.2.1 on 2019-07-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0021_auto_20190716_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='asdfadfasdfassdfassdf'),
        ),
    ]
