# Generated by Django 2.2.1 on 2019-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0022_auto_20190730_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_theme',
            name='background_color',
            field=models.CharField(max_length=10, verbose_name='Background_color1111111111'),
        ),
        migrations.AlterField(
            model_name='color_theme',
            name='header',
            field=models.CharField(max_length=10, verbose_name='Header1111111111'),
        ),
        migrations.AlterField(
            model_name='color_theme',
            name='sidebar',
            field=models.CharField(max_length=10, verbose_name='Sidebar1111111111'),
        ),
    ]
