# Generated by Django 2.2.1 on 2019-07-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0024_auto_20190730_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Basic_product_form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_image_and_videos',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Basic_product_form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pro_qty_advanced_inventory',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Basic_product_form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule_design_update',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Basic_product_form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search_engine_optimization',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Basic_product_form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set_of_images_and_videos',
            name='main_img_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Main_Image_and_Videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='special_price',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Basic_product_form'),
            preserve_default=False,
        ),
    ]
