# Generated by Django 2.2.1 on 2019-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0025_auto_20190731_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_product_form',
            name='set_pro_new_from',
            field=models.CharField(max_length=20, verbose_name='set_pro_new_from'),
        ),
        migrations.AlterField(
            model_name='basic_product_form',
            name='set_pro_new_to',
            field=models.CharField(max_length=20, verbose_name='set_pro_new_to'),
        ),
        migrations.AlterField(
            model_name='schedule_design_update',
            name='schedule_design_end',
            field=models.DateField(max_length=20, verbose_name='schedule_design_end'),
        ),
        migrations.AlterField(
            model_name='schedule_design_update',
            name='schedule_design_start',
            field=models.DateField(max_length=20, verbose_name='schedule_design_start'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price_from',
            field=models.CharField(max_length=20, verbose_name='special_price_from'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price_to',
            field=models.CharField(max_length=20, verbose_name='special_price_to'),
        ),
    ]
