# Generated by Django 2.2.1 on 2019-07-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0026_auto_20190731_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_design_update',
            name='schedule_design_end',
            field=models.CharField(max_length=20, verbose_name='schedule_design_end'),
        ),
        migrations.AlterField(
            model_name='schedule_design_update',
            name='schedule_design_start',
            field=models.CharField(max_length=20, verbose_name='schedule_design_start'),
        ),
    ]
