# Generated by Django 2.2.1 on 2019-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0027_auto_20190731_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_qty_advanced_inventory',
            name='back_orders',
            field=models.CharField(max_length=40, verbose_name='back_orders'),
        ),
    ]
