# Generated by Django 2.2.1 on 2019-08-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0028_auto_20190731_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_of_images_and_videos',
            name='url_of_videos',
        ),
    ]
