# Generated by Django 2.2.1 on 2019-08-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0029_remove_set_of_images_and_videos_url_of_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='main_image_and_videos',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='pro_qty_advanced_inventory',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='schedule_design_update',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='search_engine_optimization',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='special_price',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='variant_products',
            name='main_product_id',
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='adv_inventory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Pro_qty_advanced_inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='contents_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Contents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='main_image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Main_Image_and_Videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='schedule_design_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Schedule_design_update'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='seo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Search_Engine_Optimization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='special_price_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Special_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='variant_products_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Variant_products'),
            preserve_default=False,
        ),
    ]
