# Generated by Django 2.2.1 on 2019-08-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0030_auto_20190813_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_product_form',
            name='variant_products_id',
        ),
        migrations.DeleteModel(
            name='Variant_products',
        ),
    ]
