# Generated by Django 2.2.1 on 2019-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0032_user_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_registration',
        ),
    ]
