# Generated by Django 2.2.1 on 2019-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0033_delete_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_image',
            name='image',
            field=models.FileField(blank=True, upload_to='banner_image/'),
        ),
        migrations.AlterField(
            model_name='main_image_and_videos',
            name='main_image',
            field=models.FileField(blank=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='main_image_and_videos',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='product_thumbanails/'),
        ),
        migrations.AlterField(
            model_name='main_image_and_videos',
            name='url_of_videos',
            field=models.FileField(blank=True, upload_to='product_videos/'),
        ),
        migrations.AlterField(
            model_name='set_of_images_and_videos',
            name='url_of_images',
            field=models.FileField(blank=True, upload_to='set_of_product_images/'),
        ),
    ]
