# Generated by Django 2.2.1 on 2019-09-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0036_auto_20190910_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_image',
            name='image',
            field=models.FileField(blank=True, upload_to='./banner_image/'),
        ),
    ]
