# Generated by Django 2.2.1 on 2019-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0038_auto_20190911_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/%Y/%m/%d/'),
        ),
    ]
