# Generated by Django 2.2.1 on 2019-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0039_auto_20190911_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
