# Generated by Django 2.2.1 on 2019-10-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0040_auto_20190911_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_product_form',
            name='adv_inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Pro_qty_advanced_inventory'),
        ),
        migrations.AlterField(
            model_name='basic_product_form',
            name='contents_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Contents'),
        ),
        migrations.AlterField(
            model_name='basic_product_form',
            name='main_image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Main_Image_and_Videos'),
        ),
        migrations.AlterField(
            model_name='basic_product_form',
            name='schedule_design_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Schedule_design_update'),
        ),
        migrations.AlterField(
            model_name='basic_product_form',
            name='seo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Search_Engine_Optimization'),
        ),
        migrations.AlterField(
            model_name='basic_product_form',
            name='special_price_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Special_price'),
        ),
    ]
