# Generated by Django 2.2.1 on 2019-10-23 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0041_auto_20191011_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_of_images_and_videos',
            name='main_img_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_of_images_and_videos', to='E_Commerce.Main_Image_and_Videos'),
        ),
    ]
