# Generated by Django 2.2.1 on 2019-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0043_basic_product_form_avg_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_product_form',
            name='review_count',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Review_count'),
        ),
    ]
