# Generated by Django 2.2.1 on 2019-12-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0044_basic_product_form_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_per_gm', models.CharField(max_length=10, verbose_name='actual_per_gm')),
                ('sale_per_gm', models.CharField(max_length=10, verbose_name='sale_per_gm')),
                ('actual_total_pcs_price', models.CharField(max_length=10, verbose_name='actual_total_pcs_price')),
                ('sale_total_pcs_price', models.CharField(max_length=10, verbose_name='sale_total_pcs_price')),
                ('actual_pckg_cost', models.CharField(max_length=10, verbose_name='actual_pckg_cost')),
                ('sale_pckg_cost', models.CharField(max_length=10, verbose_name='sale_pckg_cost')),
                ('actual_parcel_cost', models.CharField(max_length=10, verbose_name='actual_parcel_cost')),
                ('sale_parcel_cost', models.CharField(max_length=10, verbose_name='sale_parcel_cost')),
                ('actual_other_cost', models.CharField(max_length=10, verbose_name='actual_other_cost')),
                ('sale_other_cost', models.CharField(max_length=10, verbose_name='sale_other_cost')),
                ('actual_total_price', models.CharField(max_length=10, verbose_name='actual_total_price')),
                ('sale_total_price', models.CharField(max_length=10, verbose_name='sale_total_price')),
                ('strike_price', models.CharField(max_length=10, verbose_name='strike_price')),
                ('strike_start', models.DateField(verbose_name='strike_start')),
                ('strike_end', models.DateField(verbose_name='strike_end')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='E_Commerce.Basic_product_form')),
            ],
        ),
    ]
