# Generated by Django 2.2.1 on 2019-12-13 14:37

from django.db import migrations, models
# import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0045_product_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_prices',
            name='product_id',
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='product_prices',
            # field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Product_prices'),
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='product_prices'),
            
        ),
    ]
