# Generated by Django 2.2.1 on 2019-12-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0047_auto_20191213_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_product_form',
            name='product_prices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Product_prices'),
            preserve_default=False,
        ),
    ]
