# Generated by Django 2.2.1 on 2019-12-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0049_auto_20191213_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_prices',
            name='product_id',
        ),
    ]
