# Generated by Django 2.2.1 on 2019-12-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0050_remove_product_prices_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_prices',
        ),
    ]
