# Generated by Django 2.2.1 on 2019-12-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0052_auto_20191213_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_product_form',
            name='product_prices',
        ),
        migrations.AddField(
            model_name='product_prices',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='E_Commerce.Basic_product_form'),
        ),
    ]
