# Generated by Django 2.2.1 on 2019-12-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0053_auto_20191214_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_prices',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='E_Commerce.Basic_product_form'),
        ),
    ]
