# Generated by Django 2.2.1 on 2019-12-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0054_auto_20191214_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_prices',
            name='product_id',
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='product_prices',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Product_prices'),
        ),
    ]
