# Generated by Django 2.2.1 on 2019-12-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0055_auto_20191214_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_product_form',
            old_name='product_prices',
            new_name='product_prices_id',
        ),
    ]
