# Generated by Django 2.2.1 on 2019-12-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0056_auto_20191214_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_product_form',
            name='product_prices_id',
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='product_diff_prices_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Product_prices'),
        ),
    ]
