# Generated by Django 2.2.1 on 2019-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0057_auto_20191214_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_product_form',
            name='product_diff_prices_id',
        ),
    ]
