# Generated by Django 2.2.1 on 2019-12-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0058_remove_basic_product_form_product_diff_prices_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_product_form',
            name='product_diff_prices_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Product_prices'),
        ),
    ]
