# Generated by Django 2.2.1 on 2019-12-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0059_basic_product_form_product_diff_prices_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_product_form',
            name='product_diff_prices_id',
        ),
        migrations.DeleteModel(
            name='Product_prices',
        ),
    ]
