# Generated by Django 2.2.1 on 2019-12-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0060_auto_20191216_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_per_gm', models.CharField(max_length=10, verbose_name='actual_per_gm')),
                ('sale_per_gm', models.CharField(max_length=10, verbose_name='sale_per_gm')),
                ('actual_total_pcs_price', models.CharField(max_length=10, verbose_name='actual_total_pcs_price')),
                ('sale_total_pcs_price', models.CharField(max_length=10, verbose_name='sale_total_pcs_price')),
                ('actual_pckg_cost', models.CharField(max_length=10, verbose_name='actual_pckg_cost')),
                ('sale_pckg_cost', models.CharField(max_length=10, verbose_name='sale_pckg_cost')),
                ('actual_parcel_cost', models.CharField(max_length=10, verbose_name='actual_parcel_cost')),
                ('sale_parcel_cost', models.CharField(max_length=10, verbose_name='sale_parcel_cost')),
                ('actual_other_cost', models.CharField(max_length=10, verbose_name='actual_other_cost')),
                ('sale_other_cost', models.CharField(max_length=10, verbose_name='sale_other_cost')),
                ('actual_total_price', models.CharField(max_length=10, verbose_name='actual_total_price')),
                ('sale_total_price', models.CharField(max_length=10, verbose_name='sale_total_price')),
                ('strike_price', models.CharField(max_length=10, verbose_name='strike_price')),
                ('strike_start', models.DateField(verbose_name='strike_start')),
                ('strike_end', models.DateField(verbose_name='strike_end')),
            ],
        ),
        migrations.AddField(
            model_name='basic_product_form',
            name='product_prices_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Product_prices'),
        ),
    ]
