# Generated by Django 2.2.1 on 2019-12-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0061_auto_20191216_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_product_form',
            name='product_prices_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_product_form', to='E_Commerce.Product_prices'),
        ),
    ]
