# Generated by Django 2.2.1 on 2019-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0063_auto_20191216_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_price',
            name='actual_other_cost',
            field=models.CharField(default='0', max_length=10, verbose_name='actual_other_cost'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='actual_parcel_cost',
            field=models.CharField(default='0', max_length=10, verbose_name='actual_parcel_cost'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='actual_pckg_cost',
            field=models.CharField(default='0', max_length=10, verbose_name='actual_pckg_cost'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='actual_per_gm',
            field=models.CharField(default='0', max_length=10, verbose_name='actual_per_gm'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='actual_total_pcs_price',
            field=models.CharField(default='0', max_length=10, verbose_name='actual_total_pcs_price'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='actual_total_price',
            field=models.CharField(default='0', max_length=10, verbose_name='actual_total_price'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='sale_other_cost',
            field=models.CharField(default='0', max_length=10, verbose_name='sale_other_cost'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='sale_parcel_cost',
            field=models.CharField(default='0', max_length=10, verbose_name='sale_parcel_cost'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='sale_pckg_cost',
            field=models.CharField(default='0', max_length=10, verbose_name='sale_pckg_cost'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='sale_per_gm',
            field=models.CharField(default='0', max_length=10, verbose_name='sale_per_gm'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='sale_total_pcs_price',
            field=models.CharField(default='0', max_length=10, verbose_name='sale_total_pcs_price'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='sale_total_price',
            field=models.CharField(default='0', max_length=10, verbose_name='sale_total_price'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='strike_end',
            field=models.DateField(blank=True, null=True, verbose_name='strike_end'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='strike_price',
            field=models.CharField(default='0', max_length=10, verbose_name='strike_price'),
        ),
        migrations.AddField(
            model_name='special_price',
            name='strike_start',
            field=models.DateField(blank=True, null=True, verbose_name='strike_start'),
        ),
        migrations.DeleteModel(
            name='Product_prices',
        ),
    ]
