# Generated by Django 2.2.1 on 2019-12-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0064_auto_20191216_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_price',
            name='disp_actual_price',
            field=models.CharField(blank=True, default='0', max_length=30, null=True, verbose_name='disp_actual_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='mfr_suggested_retailer_price',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='mfr_suggested_retailer_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_cost',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='special_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='special_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price_from',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='special_price_from'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price_to',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='special_price_to'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='strike_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='strike_end'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='strike_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='strike_start'),
        ),
    ]
