# Generated by Django 2.2.1 on 2019-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0066_auto_20191217_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_price',
            name='strike_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='strike_end'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='strike_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='strike_start'),
        ),
    ]
