# Generated by Django 2.2.1 on 2019-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0067_auto_20191217_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_price',
            name='strike_end',
            field=models.DateField(blank=True, null=True, verbose_name='strike_end'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='strike_start',
            field=models.DateField(blank=True, null=True, verbose_name='strike_start'),
        ),
    ]
