# Generated by Django 2.2.1 on 2019-12-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0068_auto_20191217_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_price',
            name='sale_status',
            field=models.BooleanField(default=False),
        ),
    ]
