# Generated by Django 2.2.1 on 2019-12-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0069_special_price_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_price',
            name='actual_other_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='actual_other_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='actual_parcel_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='actual_parcel_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='actual_pckg_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='actual_pckg_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='actual_per_gm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='actual_per_gm'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='actual_total_pcs_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='actual_total_pcs_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='actual_total_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='actual_total_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='disp_actual_price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='disp_actual_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='mfr_suggested_retailer_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='mfr_suggested_retailer_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='sale_other_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sale_other_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='sale_parcel_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sale_parcel_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='sale_pckg_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sale_pckg_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='sale_per_gm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sale_per_gm'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='sale_total_pcs_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sale_total_pcs_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='sale_total_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sale_total_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='special_cost'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='special_price'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price_from',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='special_price_from'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='special_price_to',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='special_price_to'),
        ),
        migrations.AlterField(
            model_name='special_price',
            name='strike_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='strike_price'),
        ),
    ]
