# Generated by Django 2.2.1 on 2019-12-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0070_auto_20191222_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_product_form',
            name='product_prices',
            field=models.CharField(default=1, max_length=50, verbose_name='product_name'),
            preserve_default=False,
        ),
    ]
