# Generated by Django 2.2.1 on 2019-12-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0071_basic_product_form_product_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_product_form',
            name='product_prices',
        ),
    ]
