# Generated by Django 2.2.1 on 2019-09-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0040_auto_20190911_0057'),
        ('flipmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.CharField(max_length=3, verbose_name='cart_product_quantity')),
                ('product_price', models.CharField(max_length=8, verbose_name='product_price')),
                ('total_price', models.CharField(max_length=8, verbose_name='Total')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_to_cart', to='E_Commerce.Basic_product_form')),
            ],
        ),
    ]
