# Generated by Django 2.2.1 on 2019-09-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0002_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_to_cart', to='flipmart.User_registration'),
            preserve_default=False,
        ),
    ]
