# Generated by Django 2.2.1 on 2019-09-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0003_add_to_cart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='total_price',
        ),
    ]
