# Generated by Django 2.2.1 on 2019-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0004_remove_add_to_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='total_price',
            field=models.BigIntegerField(null=True, verbose_name='total_price'),
        ),
    ]
