# Generated by Django 2.2.1 on 2019-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0005_user_registration_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='total_price',
            field=models.BigIntegerField(default=0, null=True, verbose_name='total_price'),
        ),
    ]
