# Generated by Django 2.2.1 on 2019-10-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0042_auto_20191024_0217'),
        ('flipmart', '0006_auto_20191011_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(max_length=1, verbose_name='ratings')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='E_Commerce.Basic_product_form')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='flipmart.User_registration')),
            ],
        ),
    ]
