# Generated by Django 2.2.1 on 2019-10-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='text'),
        ),
    ]
