# Generated by Django 2.2.1 on 2019-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0008_auto_20191029_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='sub_total',
            field=models.CharField(default=1, max_length=8, verbose_name='Sub_total'),
            preserve_default=False,
        ),
    ]
