# Generated by Django 2.2.1 on 2019-10-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0044_basic_product_form_review_count'),
        ('flipmart', '0010_wish_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_comparision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comparision', to='E_Commerce.Basic_product_form')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comparision', to='flipmart.User_registration')),
            ],
        ),
    ]
