# Generated by Django 2.2.1 on 2019-10-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0012_user_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_delivery_address',
            name='temporary_address',
            field=models.BooleanField(default=False),
        ),
    ]
