# Generated by Django 2.2.1 on 2019-10-30 14:54

from django.db import migrations, models
import django.utils.timezone



class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0013_user_delivery_address_temporary_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_delivery_address',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='user_delivery_address',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=True,
        ),
    ]
