# Generated by Django 2.2.1 on 2019-10-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0014_auto_20191030_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_delivery_address',
            name='time',
        ),
    ]
