# Generated by Django 2.2.1 on 2019-10-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0017_auto_20191030_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_delivery_address',
        ),
    ]
