# Generated by Django 2.2.1 on 2019-10-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0020_auto_20191031_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_address_of_customer',
            new_name='User_delivery_address',
        ),
    ]
