# Generated by Django 2.2.1 on 2019-10-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0021_auto_20191031_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_delivery_address',
        ),
    ]
