# Generated by Django 2.2.1 on 2019-10-31 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0022_delete_user_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_delivery_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, null=True, verbose_name='company_name')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('house_no_and_street_name', models.CharField(max_length=50, verbose_name='house_no')),
                ('apartment', models.CharField(max_length=40, verbose_name='apartment')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
                ('pincode', models.CharField(max_length=10, verbose_name='pincode')),
                ('order_notes', models.CharField(max_length=200, verbose_name='order_notes')),
                ('temporary_address', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_address', to='flipmart.User_registration')),
            ],
        ),
    ]
