# Generated by Django 2.2.1 on 2019-10-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0023_user_delivery_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_delivery_address',
            new_name='Delivery_address_of_customer',
        ),
    ]
