# Generated by Django 2.2.1 on 2019-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0024_auto_20191031_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address_of_customer',
            name='payment_method',
            field=models.CharField(default='COD', max_length=20, verbose_name='order_notes'),
            preserve_default=False,
        ),
    ]
