# Generated by Django 2.2.1 on 2019-10-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0025_delivery_address_of_customer_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_of_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, null=True, verbose_name='company_name')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('house_no_and_street_name', models.CharField(max_length=50, verbose_name='house_no')),
                ('apartment', models.CharField(max_length=40, verbose_name='apartment')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
                ('pincode', models.CharField(max_length=10, verbose_name='pincode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_of_customer', to='flipmart.User_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_notes', models.CharField(max_length=200, verbose_name='order_notes')),
                ('temporary_address', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=20, verbose_name='payment_method')),
                ('total_amount', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='flipmart.Add_to_cart')),
                ('customer_addr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='flipmart.Address_of_customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='flipmart.User_registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery_address_of_customer',
        ),
    ]
