# Generated by Django 2.2.1 on 2019-10-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0027_remove_order_details_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='cart_id',
        ),
    ]
