# Generated by Django 2.2.1 on 2019-10-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0028_remove_order_details_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='temporary_address',
        ),
        migrations.AddField(
            model_name='address_of_customer',
            name='temporary_address',
            field=models.BooleanField(default=False),
        ),
    ]
