# Generated by Django 2.2.1 on 2019-10-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0029_auto_20191031_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_of_customer',
            old_name='temporary_address',
            new_name='permanent_address',
        ),
    ]
