# Generated by Django 2.2.1 on 2019-12-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0044_basic_product_form_review_count'),
        ('flipmart', '0030_auto_20191031_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.CharField(max_length=5, verbose_name='product_quantity')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='E_Commerce.Basic_product_form')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='flipmart.User_registration')),
            ],
        ),
    ]
