# Generated by Django 2.2.1 on 2019-12-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0069_special_price_sale_status'),
        ('flipmart', '0031_purchase_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='customer_addr_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='purchase_history',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='purchase_history',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='order_details',
            name='onsale',
            field=models.BooleanField(default=False, verbose_name='on_sale'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='price',
            field=models.CharField(max_length=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='E_Commerce.Basic_product_form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='product_quantity',
            field=models.CharField(max_length=5, null=True, verbose_name='product_quantity'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='purchase_history_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='flipmart.purchase_history'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_details',
            name='result',
            field=models.CharField(max_length=5, null=True, verbose_name='result'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='sub_total',
            field=models.CharField(default=1, max_length=8, verbose_name='Sub_total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='customer_addr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='flipmart.Address_of_customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='order_notes',
            field=models.CharField(default=1, max_length=200, verbose_name='order_notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='payment_method',
            field=models.CharField(default=1, max_length=20, verbose_name='payment_method'),
            preserve_default=False,
        ),
    ]
