# Generated by Django 2.2.1 on 2019-12-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipmart', '0032_auto_20191222_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='onsale',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='purchase_history_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='result',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='purchase_history',
            name='customer_addr_id',
        ),
        migrations.RemoveField(
            model_name='purchase_history',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='purchase_history',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='purchase_history',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='purchase_history',
            name='user_id',
        ),
    ]
