# Generated by Django 2.2.1 on 2019-12-22 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce', '0069_special_price_sale_status'),
        ('flipmart', '0035_auto_20191222_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='onsale',
            field=models.BooleanField(default=False, verbose_name='on_sale'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='price',
            field=models.CharField(max_length=5, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='E_Commerce.Basic_product_form'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='product_quantity',
            field=models.CharField(max_length=5, null=True, verbose_name='product_quantity'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='purchase_history_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='flipmart.purchase_history'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='result',
            field=models.CharField(max_length=5, null=True, verbose_name='result'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='sub_total',
            field=models.CharField(default=0, max_length=8, verbose_name='Sub_total'),
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='customer_addr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='flipmart.Address_of_customer'),
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='order_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='order_notes'),
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='payment_method'),
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='user_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='flipmart.User_registration'),
        ),
    ]
